name: Java CI with Gradle

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-java:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Runs on multiple OS platforms

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Print Greeting Message
      run: echo "Hi, I am from COSC 1209 class"

    - name: Check if gradlew exists
      run: ls -l gradlew || echo "gradlew not found!"
    
    - name: Grant execute permission for Gradle (Linux & Mac)
      if: runner.os != 'Windows'
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      shell: bash

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5  # Updated version
      with:
        image: nanajanashia/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
